### ISSUE TITLE
Training the weights.caffemodel

### ISSUE THREAD

**Issue by mrocr** [waldol1/HisDB#1]
@ctensmeyer @herobd @cwig Thank you for your hard work.
For `Task 3 - Textline segmentation`, how did you train the [`weights.caffemodel`](https://github.com/ctensmeyer/HisDB/blob/master/task_3/weights.caffemodel)?

**Comment by ctensmeyer** [comment]
We used the Caffe framework using the model arch specified in the repo.

**Comment by mrocr** [comment]
So you used your own [Caffe fork](https://github.com/ctensmeyer/caffe) along with the [model structure](https://github.com/ctensmeyer/HisDB/blob/master/task_3/model.prototxt) that you set.

1- How to  prepare the training data?
2- How to actually train?
3- How does HisDB performance compared to start_follow_read?

Your help would be appreciated.

**Comment by ctensmeyer** [comment]
IIRC
1) Downsample images (1/4th or smaller).  Cut up images into overlapping patches (e.g. 256.256) for training inputs.  For the GT, render the baselines as 7-pixel thick lines to create a binary mask for each image.
2) To actually train, I set up a Caffe solver file and a training model.prototxt and then used the `caffe train` cmd.
3) SFR probably does better.  We haven't done a direct comparison because they output different representations of text lines.
